#cloud-config
repo_update: true

packages:
- nginx
- neofetch

runcmd:
- systemctl start nginx
- systemctl enable nginx

users:
- default
- name: ${ssh_user_name}
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash